services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04
    hostname: sqlserver
    container_name: encaixa_sqlserver
    networks:
      - encaixa-net
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "timeout 15 bash -c 'if [[ -f /var/opt/mssql/log/errorlog ]]; then grep -q \"SQL Server is now ready\" /var/opt/mssql/log/errorlog; else exit 1; fi'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    volumes:
      - sql-data:/var/opt/mssql
      - ./sql-logs:/var/opt/mssql/log
    deploy:
      resources:
        limits:
          memory: 2.5GB

  encaixaapi:
    build:
      context: ./EncaixaAPI
      dockerfile: Dockerfile
    container_name: encaixa_api
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - encaixa-net
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=EncaixaDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;Encrypt=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      JwtSettings__ValidAudience: "http://host.docker.internal"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https:/https

networks:
  encaixa-net:
    driver: bridge

volumes:
  sql-data: